<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find ceerii_mobile_bot)/urdf/xacro/transmissions.xacro"/>

    <xacro:property name="wheel_mass" value="0.015" />
    <xacro:property name="wheel_radius" value="0.035" />
    <xacro:property name="wheel_height" value="0.008" />

    <xacro:property name="passive_wheel_mass" value="0.02" />
    <xacro:property name="passive_wheel_radius" value="0.01" />
    <xacro:property name="passive_wheel_holder_mass" value="0.02" />
    <xacro:property name="passive_wheel_holder_radius" value="0.01" />
    <xacro:property name="passive_wheel_holder_height" value="0.018" />

    <xacro:property name="passive_wheel_inertia_calc" value="${(2/5) * passive_wheel_mass * (passive_wheel_radius * passive_wheel_radius)}" />
    <xacro:property name="wheel_inertia_calc_izz" value="${(1/2) * wheel_mass * (wheel_radius * wheel_radius)}" />
    <xacro:property name="wheel_inertia_calc" value="${(1/12) * wheel_mass * ((3 * (wheel_radius * wheel_radius)) + (wheel_height * wheel_height))}" />
    <xacro:property name="passive_wheel_holder_inertia_calc_izz" value="${(1/2) * passive_wheel_holder_mass * (passive_wheel_holder_radius * passive_wheel_holder_radius)}" />
    <xacro:property name="passive_wheel_holder_inertia_calc" value="${(1/12) * passive_wheel_holder_mass * ((3 * (passive_wheel_holder_radius * passive_wheel_holder_radius)) + (passive_wheel_holder_height * passive_wheel_holder_height))}" />

    
    <xacro:macro name="wheel" params="prefix y_offset">
        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_height}" />
                </geometry>
                <material name="black" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_height}" />
                </geometry>
            </collision>
            <inertial>
                <mass value="${wheel_mass}"/>
                <inertia ixx="${wheel_inertia_calc}" ixy="0.0" ixz="0.0" iyy="${wheel_inertia_calc}" iyz="0.0" izz="${wheel_inertia_calc_izz}"/>
            </inertial>
        </link>

        <joint name="joint_chasis__${prefix}_wheel" type="continuous">
            <parent link="chasis"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="0 ${y_offset} 0" rpy="0 0 0" />
            <axis xyz="0 1 0"/>
        </joint>

        <!-- Robot Joints' Transmission -->
        <xacro:wheel_transmission wheelJointName="joint_chasis__${prefix}_wheel"  />
    </xacro:macro>

    <xacro:macro name="passive_wheel" params="z_offset x_offset">
        <link name="passive_wheel_holder">
            <visual>
                <origin xyz="0 0 ${z_offset}" />
                <geometry>
                    <cylinder radius="${passive_wheel_holder_radius}" length="${passive_wheel_holder_height}" />
                </geometry>
                <material name="black"></material>
            </visual>
            <collision>
                <origin xyz="0 0 ${z_offset}" />
                <geometry>
                    <cylinder radius="${passive_wheel_holder_radius}" length="${passive_wheel_holder_height}" />
                </geometry>
            </collision>
            <inertial>
                <mass value="${passive_wheel_holder_mass}"/>
                <inertia ixx="${passive_wheel_holder_inertia_calc}" ixy="0.0" ixz="0.0" iyy="${passive_wheel_holder_inertia_calc}" iyz="0.0" izz="${passive_wheel_holder_inertia_calc_izz}"/>
            </inertial>
        </link>

        <joint name="joint_chasis__passive_wheel_holder" type="fixed">
            <origin xyz="${x_offset} 0 0" rpy="0 0 0" />
            <parent link="chasis"/>
            <child link="passive_wheel_holder"/>
        </joint>


        <link name="passive_wheel">
            <visual>
                <geometry>
                    <sphere radius="${passive_wheel_radius}" />
                </geometry>
                <material name="black"></material>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${passive_wheel_radius}" />
                </geometry>
            </collision>
            <inertial>
                <mass value="${passive_wheel_mass}"/>
                 <inertia ixx="${passive_wheel_inertia_calc}" ixy="0.0" ixz="0.0" iyy="${passive_wheel_inertia_calc}" iyz="0.0" izz="${passive_wheel_inertia_calc}"/>
            </inertial>
        </link>

        <joint name="joint_passive_wheel_holder__passive_wheel" type="fixed">
            <origin xyz="0 0 ${z_offset - 0.005}" rpy="0 0 0" />
            <parent link="passive_wheel_holder"/>
            <child link="passive_wheel"/>
        </joint>
    </xacro:macro>
</robot>